parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - react-app
  - prettier
plugins:
  - '@typescript-eslint'
  - react-hooks
settings:
  react:
    version: detect
rules:
  '@typescript-eslint/consistent-type-definitions':
    - warn
    - type
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      ignoreRestSiblings: true
  '@typescript-eslint/no-use-before-define':
    - warn
    - functions: false
      classes: false
      variables: true
  arrow-body-style: warn
  import/no-extraneous-dependencies: warn
  import/order:
    - warn
    - newlines-between: always
      alphabetize:
        order: 'asc'
  no-case-declarations: warn
  no-console: warn
  no-debugger: warn
  no-else-return: warn
  no-param-reassign: warn
  no-var: warn
  object-shorthand: warn
  padding-line-between-statements:
    - warn
    - blankLine: always
      prev: '*'
      next: class
    - blankLine: always
      prev: '*'
      next: for
    - blankLine: always
      prev: '*'
      next: function
    - blankLine: always
      prev: '*'
      next: if
    - blankLine: always
      prev: '*'
      next: return
    - blankLine: always
      prev: '*'
      next: switch
    - blankLine: always
      prev: '*'
      next: try
    - blankLine: always
      prev: '*'
      next: while
    - blankLine: always
      prev: block-like
      next:
        - let
        - const
  prefer-const: warn
  react/jsx-boolean-value: warn
  react/jsx-curly-brace-presence: warn
  react/jsx-key: warn
  react/jsx-sort-props:
    - warn
    - callbacksLast: true
      reservedFirst: true
      shorthandLast: true
  react/no-array-index-key: warn
  react/prefer-stateless-function: warn
  react/self-closing-comp: warn
  react-hooks/rules-of-hooks: error
  yoda: warn
